run_model_func: pv_site_production.models.psp.get_model
model_path: s3://pvsite-ml-models-development/models/model-0.2.0.pkl

nwp:
  cls: psp.data.data_sources.nwp.NwpDataSource
  kwargs:
    path: s3://nowcasting-nwp-development/data/latest.zarr

pv_metadata_path: s3://pvsite-ml-models-development/meta_inferred.csv

pv_db_url: ${OCF_PV_DB_URL}
