run_model_func: forecast_inference.models.psp.get_model
model_path: s3://uk-site-forecaster-models-${OCF_ENVIRONMENT}/models/model-0.4.0.pkl

nwp:
  cls: psp.data_sources.nwp.NwpDataSource
  args:
    - ${NWP_ZARR_PATH}
  kwargs:
    time_dim_name: init_time
    value_name: UKV
    y_is_ascending: false
    coord_system: 27700

pv_metadata_path: s3://pvsite-ml-models-${OCF_ENVIRONMENT}/meta_inferred.csv

pv_db_url: ${OCF_PV_DB_URL}
