run_model_func: pv_site_production.models.psp.get_model
model_path: s3://pvsite-ml-models-development/models/latest.pkl

nwp:
  cls: pv_site_production.data.nwp_data_sources.NwpDataSource
  kwargs:
    path: s3://nowcasting-nwp-development/data/latest.netcdf

pv_metadata_path: s3://pvsite-ml-models-development/meta_inferred.csv

pvsite_db_url: ${OCF_PV_DB_URL}
