
name: Branch CI (Python)
run-name: 'Branch CI for ${{ github.event.head_commit.message }} by ${{ github.actor }}'

on:  
  push:
    branches-ignore: [ "main" ]
    paths-ignore: ['README.md']

permissions:
  packages: write
  contents: read

jobs:
  branch-ci:
    uses: openclimatefix/.github/.github/workflows/branch_ci.yml@v2.0.0
    secrets: inherit
    with:
      enable_linting: false
      enable_typechecking: false
      tests_folder: forecast-inference/tests
      containerfile: "infrastructure/Dockerfile.forecast-inference"

  # TODO add database-cleanup job