name: Build forecast-archive docker

on:
  push:

jobs:
  build-forecast-archive-docker:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build
        run: make build-forecast-archive
