name: Build inference service

on:
  push:

jobs:
  push_to_registry:
    name: Build docker
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        run: make build-inference
