name: Lint Python
on: [push]
jobs:
  call-run-python-linters:
    uses: openclimatefix/.github/.github/workflows/python-lint.yml@main

  # The previous job does most of the work but we don't have an OCF workflow for mypy yet so we
  # specify it here.
  mypy:
    name: Run mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: snok/install-poetry@v1
        with:
          version: 1.3.2

      - name: Install python dependencies
        run: |
          poetry install

      - name: Run mypy
        run: poetry run mypy pv_site_production tests
