name: Bump version and release dockers
on:
  push:
    branches: main

jobs:
  bump-version:
    uses: openclimatefix/.github/.github/workflows/bump-version.yml@standalone-release
    id: bumper

  release-forecast-inference-docker:
    needs: bump-version
    uses: openclimatefix/.github/.github/workflows/docker-release-only.yml@standalone-release
    secrets: inherit
    with:
      image_base_name: pvsite_forecast
      docker_file: infrastructure/Dockerfile.forecast-inference
      tag_value: ${{ jobs.bumper.outputs.new_ver }}

  release-database-cleanup-docker:
    needs: bump-version
    uses: openclimatefix/.github/.github/workflows/docker-release-only.yml@standalone-release
    secrets: inherit
    with:
      image_base_name: pvsite_database_cleanup
      docker_file: infrastructure/Dockerfile.database-cleanup
      tag_value: ${{ jobs.bumper.outputs.new_ver }}
