name: Bump version and auto-release (docker)
on:
  push:
    # branches:
      # - main

jobs:
  docker-release:
    needs: [bump-version]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - run: echo ${{ needs.bump-version.outputs.new_tag }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          # TODO make more flexible
          images: |
            openclimatefix/${{ inputs.image_base_name }}
          tags: |
            type=raw,value=${{ needs.bump-version.outputs.new_tag }}
          flavor: |
            latest=true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: openclimatefix
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ inputs.docker_file }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  # call-run-docker-release:
  #   uses: openclimatefix/.github/.github/workflows/docker-release.yml@main
  #   secrets:
  #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  #     DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  #   with:
  #     image_base_name: pvsite_forecast
  #     docker_file: infrastructure/Dockerfile
