name: Tagged CI - Database Cleanup
run-name: 'Tagged CI (Database cleanup) for ${{ github.ref_name }} by ${{ github.actor }}'
on:
  push:
    tags: ["v*.*.*"]
permissions:
  packages: write
  contents: read
  id-token: write
jobs:
  tagged-ci-database-cleanup:
    uses: openclimatefix/.github/.github/workflows/tagged_ci.yml@v2.0.1
    secrets: inherit
    with:
      containerfile: "infrastructure/Dockerfile.database-cleanup"
      image_base_name: "openclimatefix/pvsite_database_cleanup"
