name: Tests and lint

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  test_and_lint_database_cleanup:
    name: Run tests and lint - database-cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install and configure poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: poetry

      - name: Install and configure poetry
        run: cd database-cleanup && poetry install

      - name: Run tests
        run: cd database-cleanup && make test

      - name: Run lint
        run: cd database-cleanup && make lint

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
