name: Tests

on:
  push:
  schedule:
    - cron: "0 12 * * 1"

jobs:
  push_to_registry:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Install linux dependencies
        run: sudo apt-get install -y libgeos-dev

      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install and configure poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2

      - name: Install python dependencies
        run: poetry install --no-interaction

      - name: Run tests
        run: make test

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
