name: Tests and lint

on:
  push:

jobs:
  test_and_lint_forecast_inference:
    name: Run tests and lint - forecast-inference
    runs-on: ubuntu-latest
    steps:
      - name: Install linux dependencies
        run: sudo apt-get install -y libgeos-dev

      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install and configure poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2

      - name: Run tests
        run: cd forecast-inference && make test

      - name: Run lint
        run: cd forecast-inference && make lint

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  test_and_lint_database_cleanup:
    name: Run tests and lint - database-cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install and configure poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2

      - name: Run tests
        run: cd database-cleanup && make test

      - name: Run lint
        run: cd database-cleanup && make lint

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  test_and_lint_pv_site:
    name: Run tests and lint - pv-site
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install and configure poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2

      - name: Run tests
        run: cd pv-site && make test

      - name: Run lint
        run: cd pv-site && make lint

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
